export const Types = {
    CUSTOMER_READ_SUCCESS: "CUSTOMER_READ_SUCCESS",
    CUSTOMER_CREATE_SUCCESS: "CUSTOMER_CREATE_SUCCESS",
    CUSTOMER_UPDATE_SUCCESS: "CUSTOMER_UPDATE_SUCCESS",
    CUSTOMER_DELETE_SUCCESS: "CUSTOMER_DELETE_SUCCESS",
    CUSTOMER_EDIT_SUCCESS: "CUSTOMER_EDIT_SUCCESS",
}