export const Types = {
    COUNTRY_READ_SUCCESS: "COUNTRY_READ_SUCCESS",
    COUNTRY_CREATE_SUCCESS: "COUNTRY_CREATE_SUCCESS",
    COUNTRY_UPDATE_SUCCESS: "COUNTRY_UPDATE_SUCCESS",
    COUNTRY_DELETE_SUCCESS: "COUNTRY_DELETE_SUCCESS",
    COUNTRY_EDIT_SUCCESS: "COUNTRY_EDIT_SUCCESS",
}